### ISSUE TITLE
Add frame suppression to microcode?

### ISSUE THREAD

**Issue by MattWindsor91** [septract/starling-tool#104]
One way of dealing with referential transparency might be to add a new action

```
forget LVALUE
```

into the `Microcode` representation used in the post-array Starling command semantics.  The semantics of this action would be to prevent `LVALUE` from being framed, but not assign it to a value.

Thus, if we add custom command semantics, symbolic commands that affect a heap can now be represented as e.g. (in aspirational Starling syntax, I'll propose this in a later issue):

```
command Lock(shared int &heap, thread int lockID)
{
    forget heap, %{Lock(#1)}(lockID)
} 
```

This generalises #81.

**Comment by septract** [comment]
Just to note that `forget` is a command in the v popular Boogie intermediate verification language (where it's called `havoc`). Perhaps this suggests it's a good choice? See [the Boogie reference manual](https://research.microsoft.com/en-us/um/people/leino/papers/krml178.pdf), S9.4:

**Comment by MattWindsor91** [comment]
This is done now, I believe.
