### ISSUE TITLE
Case study: Reader/Writer lock

### ISSUE THREAD

**Issue by MattWindsor91** [septract/starling-tool#3]
As per the maths note.

Compared to the ticketed lock, this requires implementation or sidestepping of:
- [x] Iterated-separation view constraints (theory? syntax?) 
- [ ] ~~Function calls~~
- [ ] ~~Method calls~~
- [ ] ~~Possibly an abbreviated syntax for constraining permutations of view conjunctions (like the `{inR(), noR(), noW(), noRW()} ∗ {inR(), noR(), noW(), noRW()}` notation used in the note).~~

**Comment by mjp41** [comment]
In the [commit](https://github.com/septract/starling-tool/commit/53d0267503bc2658b6153a7736b2d52cf032be8a) I just pushed. I have created an example that would allow us to just address the:
   Iterated-separation view constraints (theory? syntax?) 

This might be worth increasing in priority. Thoughts?

**Comment by MattWindsor91** [comment]
Yeah, I think this is going to be the next example we tackle.

Just going to come back to the shorthand interacting constraint syntax—probably not worth looking at any time soon, but this came up again with the Peterson proof.  So there is some scope for it being mildly useful.

**Comment by MattWindsor91** [comment]
Depends on #22.

**Comment by MattWindsor91** [comment]
This is just waiting on some PRQs I think?

**Comment by MattWindsor91** [comment]
Closing this now, we basically have this lock.
