### ISSUE TITLE
drop iter[n] in iterated view declarations

### ISSUE THREAD

**Issue by septract** [septract/starling-tool#84]
Instead of writing
> ```view  iter[n] blah();```

we should write
> ```view iter blah();``` 

This is a tiny tweak to the parser, but right now our PLDI draft is inconsistent with Starling's syntax.

**Comment by MattWindsor91** [comment]
It'll also need some changes down the internal representation, as this currently retains the name used for `n` (the iterator is a `string option`, would need to be changed to a `bool`).

**Comment by septract** [comment]
I can do this, shouldn't be too painful. Might wait until the master branch has merged all the pending changes though.
