### ISSUE TITLE
Implement GRASShopper backend

### ISSUE THREAD

**Issue by septract** [septract/starling-tool#98]
We should be able to pass examples like `lclist-grasshopper.cvf` to GRASShopper for verification. 

With respect to the current symbolic backend, this would require: 

* Substitution of variable names into the symbolic output. Right now we have e.g. `%{ foo(#1, #2) }(var_x, var_y)` What we want is to substitute the vars into the expression so we get back: `foo(var_x, var_y)`. There may be tricky things here about handling before / after, IDK.  

* A way of encoding symbolic commands into Starling proofs. In `lclist-grasshopper.cvf` we have assignments from symbolic expressions, e.g. `heap = (%{ releaseLock(#2) }(lheap, prev))`. This isn't especially pretty, but we could hide it behind syntactic sugar. A more fundamental problem is that GRASShopper proof clauses have a requires / ensures structure, rather than a two-state encoding. Therefore we need to treat commands on heap locations specially, and right now Starling encodes them as though they're simply assertions about unknown symbolic variables. 

* Finally, we need some story about unknown side-effects. Starling commands usually encode all their effects on variables through framing - if a command doesn't mention a variable, then it can't be modified. For symbolic commands this isn't true: they have effects in the heap which aren't captured. This is important when we want to over-approx to discharge in Z3, and also when we want to optimise them away. One option if we had explicit symbolic commands is to only assume referential transparency for non-symbolic commands. I'm not sure which bits of Starling depend on this though, so there's some danger here. 

My current (v. tentative) work on this is in `mdd-grasshopper`. Hopefully I'll push more stuff to this over the next week or so.

**Comment by MattWindsor91** [comment]
Point 1 should be getting addressed by #109.

For points 2 and 3, my immediate thoughts were either:

* Add a symbolic command primitive into `Microcode` and then add a way of generating it from the AST;
* Encode symbolic commands as `assume`s—this will result, I think, in an approximation to `true`—and add a `forget` command to remove a variable from the frame (see #104 for ideas).

So, if we're encoding everything as assumes, then we might translate the command

```
<%{foo(#1, #2, #2)}(x, y)>;
```

to the `Microcode`

```
{
    assume %{foo(#1, #2, #2)}(x, y),
    forget heap,
    forget x,
    forget y,
    ...
}
```

That said, this isn't much better than what we've got, as we'd have to do a lot of mangling to convert this back into Grasshopper.

I'll think about how we might add a symbolic microcode instruction instead.  I think this would need to take a schema of which variables are modified and which aren't (I'm thinking a list of preserved variables would be more useful than a list of spoilt ones).

**Comment by MattWindsor91** [comment]
Alternatively, the above could be a decompilation of a higher-level command, and we pass the higher-level command to Grasshopper instead.

**Comment by septract** [comment]
Here's a sample of the output from lclist-grasshopper with symbolic substitution: 
```
deleteVal_C016_002:    
    After instantiation:
        Command:
            (and
                (= (after heap) (sym 'releaseLock((before curr))'))
                (= (after lheap) (before heap))
            )
        
        W/Prec:
            (and
                (sym 'has1LockG(head,(before prev),(before curr)) ')
                (=>
                    (or
                        (not (= (goal 42 b) (before _)))
                        (not (= (goal 42 a) (before prev)))
                    )
                    (sym 'has1LockG(head,(goal 42 a),(goal 42 b)) ')
                )
                (=>
                    (or
                        (not (= (goal 42 b) (before _)))
                        (not (= (goal 42 a) (before prev)))
                    )
                    (not (= (before prev) (goal 42 a)))
                )
                (=>
                    (or
                        (not (= (goal 42 b) (before _)))
                        (not (= (goal 42 a) (before prev)))
                    )
                    (not (= (goal 42 a) (before prev)))
                )
            )
        
        Goal:
            (sym 'has1LockG(head,(goal 42 a),(goal 42 b)) ')
```

This should be translated into a Grasshopper query, written using the `procedure` keyword.

**Comment by MattWindsor91** [comment]
Ideally, we should be able to make Starling error if we try to convert a symbolic command to two-state predicate form, and thus not have to worry about the semantics of it.  However, since Z3 is preprocessing the proof, it needs access to it…

**Comment by septract** [comment]
Grasshopper backend output now looks like this:
```
procedure deleteVal_C019_002 (
    head,
    heap,
    ub,
    before_prev,
    goal_4_a,
    goal_4_b
)
requires
    ((has1LockG(head,goal_4_a,goal_4_b) ) &&
        (exists e: Node :: has1LockG(head,before_prev,e) )) ;
ensures
    (has1LockG(head,goal_4_a,goal_4_b) ) ;
{
    /*
    (and
        (= after_heap (releaseLock(before_prev) ))
        (= after_lheap before_heap)
    )
    */
}
``` 

We're now just missing types for vars and command printing (both are in @CaptainHayashi's court).

**Comment by septract** [comment]
Grasshopper outputs this clause which suggests we haven't got the variable stuff quite right: 
```
procedure deleteVal_C001_004
(
    head: Node,
    heap: Int,
    ub: Int,
    before_head: Node,
    before_heap: Int,
    before_prev: Node,
    before_ub: Int,
    before_v: Int,
    after_heap: Int,
    after_lheap: Int,
    goal_410_a: Node
)
requires
    ((isListG(head,ub) ) &&
        (sTrue() &*& (before_prev == before_head)) &&
        (sTrue() &*& (before_v < before_ub)) &&
        ((sTrue() &*& (! (goal_410_a != before_prev))) ||
            (exists e: Node :: has1LockG(head,goal_410_a,e) )))
ensures
    (exists e: Node :: has1LockG(head,goal_410_a,e) )
{
    takeLock(before_prev); 
}
```

The problem here is that Starling doesn't know that `before_head` and `head` are actually the same variables. If we rename all the instances of `head` / `ub` then the clause goes through.

**Comment by septract** [comment]
Ah, we need to qualify the predicate definitions with the variables so Starling knows how to rename them, eg: 
```
constraint has1Lock(a,b) -> %{ has1LockG(#1,#2,#3) }(head, a, b);
```

**Comment by MattWindsor91** [comment]
Closing this as we now basically have a working GRASShopper backend.
